version: '3.8'

services:
  app:
    image: jemena-camunda-poc
    ports:
      - "8080:8080"
    env_file:
      - .env
#    depends_on:
#      - artemis

#  artemis:
#    image: apache/activemq-artemis:latest
#    ports:
#      - "61616:61616"
#      - "8161:8161"